=== dmgcodevil/mingo/mingo-core/src/main/resources/xml-schema/context.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.mingo.com/schema/context"
           xmlns="http://www.mingo.com/schema/context"
           elementFormDefault="qualified">

    <!-- CONTEXT SCHEMA -->

    <!-- definition of simple types -->

    <xs:simpleType name="queryExecutorAnalyzerType">
        <xs:restriction base="xs:normalizedString">
            <xs:enumeration value="jexl"/>
            <xs:enumeration value="springEL"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="writeConcern">
        <xs:restriction base="xs:normalizedString">
            <xs:enumeration value="ACKNOWLEDGED"/>
            <xs:enumeration value="ERRORS_IGNORED"/> <!-- Deprecated. -->
            <xs:enumeration value="FSYNC_SAFE"/>
            <xs:enumeration value="FSYNCED"/>
            <xs:enumeration value="JOURNAL_SAFE"/>
            <xs:enumeration value="JOURNALED"/>
            <xs:enumeration value="MAJORITY"/>
            <xs:enumeration value="NONE"/> <!-- Deprecated. -->
            <xs:enumeration value="NORMAL"/>
            <xs:enumeration value="REPLICA_ACKNOWLEDGED"/>
            <xs:enumeration value="REPLICAS_SAFE"/>
            <xs:enumeration value="SAFE"/>
            <xs:enumeration value="UNACKNOWLEDGED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="querySet">
        <xs:complexType mixed="true">
            <xs:attribute name="path" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="option">
        <xs:complexType mixed="true">
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="value" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="options">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="option" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="config">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="benchmark" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="benchmark">
        <xs:complexType>
            <xs:attribute name="enabled" use="optional" default="false" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="defaultConverter">
        <xs:complexType>
            <xs:attribute name="class" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="converters">
        <xs:complexType>
            <xs:attribute name="package" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="querySetConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="querySet" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="queryAnalyzer">
        <xs:complexType>
            <xs:attribute name="type" type="queryExecutorAnalyzerType" use="optional" default="jexl"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="mongo">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="options" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="host" type="xs:string" use="optional" default="localhost"/>
            <xs:attribute name="port" type="xs:integer" use="optional" default="27017"/>
            <xs:attribute name="dbName" type="xs:string" use="required"/>
            <xs:attribute name="writeConcern" type="writeConcern" use="optional" default="NORMAL"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="context" >
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="config" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="querySetConfig" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="queryAnalyzer" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="mongo" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="defaultConverter" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="converters" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dmgcodevil/mingo/mingo-core/src/test/resources/mingo/test/context.xml
<?xml version="1.0" encoding="UTF-8"?>

<context xmlns="http://www.mingo.com/schema/context"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.mingo.com/schema/context
         file://../../../main/resources/xml-schema/context.xsd">


    <config>
        <benchmark enabled="false"/>
    </config>

    <querySetConfig>
        <querySet path="/mingo/test/testQuerySet.xml"/>
        <querySet path="/mingo/test/second/testQuerySet2.xml"/>
    </querySetConfig>


    <queryAnalyzer type="jexl"/>

    <mongo port="27017" host="localhost" dbName="dbTest">
        <options>
            <option name="connectTimeout" value="100"/>
        </options>
    </mongo>

    <defaultConverter class="com.mingo.mapping.convert.DefaultConverter"/>

    <converters package="com.mingo.mapping.converter.custom"/>
</context>
